### ISSUE TITLE
marker.pos cannot receive position unit:getPoint()

### ISSUE THREAD

**Issue by ucnanoman** [mrSkortch/MissionScriptingTools#70]
I've Narrowed it down further ...
Note: Yes there is a unit and group name with "POW1" in mission editor.

```
--Simplistic Version of problem
marker= {}
name = "POW1"
marker.pos = Unit.getByName(name):getPoint()     <-- marker.pos cannot receive position from unit name point 
```

Can you verify this works on your end? 
Or tell me how this might have changed and how it should be used?

I have verified that it's not that Unit.getByName("xyz") that's having the issue.
I know this works because I got it to work elsewhere.
It's position marker trying to receive the position point that's having the issue.

**Error from dcs.log:**
2022-08-14 04:56:46.250 ERROR SCRIPTING: Error while handling event [string "C:\Users\username\AppData\Local\Temp\DCS.openbeta/~mis00003EE0.lua"]:1060: attempt to index a nil value

Full Code:
```
----create a orange marker for POW when released!
POW1MARKER = {}
csar.pow1name = "POW1"               
POW1MARKER.pos = Unit.getByName(csar.pow1name):getPoint()   <-- This is where I get the dcs.log error
POW1MARKER.id = mist.marker.getNextId()
POW1MARKER.mType = 0	
POW1MARKER.readOnly = 0
POW1MARKER.text = "POW1 Located Here!"	
mist.marker.add(POW1MARKER)
```

I used Hoggit's example: (at the very bottom)
https://wiki.hoggitworld.com/view/MIST_markerAdd

```
   local v = {}
   v.pos = Unit.getByName('update'):getPoint()
   v.id = 5
   v.markForCoa = 2
   v.mType = 0                  <-- 0 for orange circle markers ... was '2'
   v.radius = 10000
   mist.marker.add(v)
```

**Comment by ucnanoman** [comment]
Update: Hoggit's Info changed at the top
I noticed that the vars look like they changed in an update?
I'll try ...
'markType' instead of 'mType'


 vars = 
 {
 pos = table pos,
 name/id = string/number name/id, 
 markType = number/string markType, 
 radius = number radius, 
 text = string text, 
 markFor = table markFor,
 markForCoa = number/string markForCoa, 
 color = table color,
 fillColor = table fillColor, 
 lineType = number lineType,
 readOnly = boolean readOnly,
 message = text message,
 fontSize = number fontSize,
 }

**Comment by mrSkortch** [comment]
If there is an error when assigning a value to a table then that error isn't a problem with mist. POW1MARKER is just a lua table, there is nothing special about it and nothing associated with mist until you actually pass that table to the mist function. Even when it gets passed to mist.marker.add it is still just a table used by that function to create the mark. 

The other reason I suggested this change was because it is possible that unit is dead. If that was the case you would also get that error nothing would be returned. 
```
local u = Unit.getByName("POW1")
if u then
  POW1MARKER.pos = u:getPoint()
else
  myLog:msg("POW1 didnt exist")
end
```

Using the code you had a problem with it worked on my end. Though I removed the csar.pow1name part because I didn't want to add csar = {}. 

![Screen_220814_162313](https://user-images.githubusercontent.com/8334336/184557110-2d7a110d-71a1-4fe1-ac19-c67047c5bb38.jpg)

[marker_example.zip](https://github.com/mrSkortch/MissionScriptingTools/files/9334208/marker_example.zip)

**Comment by ucnanoman** [comment]
Ah! okay so yea it's nothing to do with MIST then.
Thanks so much for your explanation.
So DCS changed that when a unit DIES you MUST use the event.Initiator to grab the dead unit information and can't search or any of the details outside that initiator again.

**FIX:** 
`marker.pos = _unit:getPoint() `

**FULL CODE:**
```
elseif (_event.id == 8) then -- EVENT ON DEATH of UNIT		
            env.info("Event unit - CSARUNIT Dead")

            local _unit = _event.initiator
             marker.pos = _unit:getPoint() 
```             <-- use this to grab position of dead unit
