### ISSUE TITLE
`respawnGroup` leads to drift in position and `teleportToPoint` erases bot tasks.

### ISSUE THREAD

**Issue by thomasbbrunner** [mrSkortch/MissionScriptingTools#89]
I'm trying to create a mission, in which a plane controlled by a bot respawns in its initial position when a set of conditions is met.

At first, I did this with `mist.respawnGroup(groupName, true)`. This worked, however, after multiple respawns (~500) the planes started to drift. I.e. the respawn location was not the same as the initial location when the mission started.

I then tried to use `mist.getGroupData(groupName)` to save the initial position of the planes and then used `mist.teleportToPoint` to set them back to this position. However, I observed very inconsistent behavior when using `teleportToPoint`, such as:
1. Initial altitude seems to be random (`getGroupData` only returns coordinates `x` and `y`, `z` is not included for some reason).
2. The bots forget their tasks and just fly to the waypoints (they were assigned to a CAP mission).

What is the recommended way to respawn a unit to exactly their initial location without forgetting their tasks?

**Comment by davidp57** [comment]
Hi,
I've done this usecase a lot in my VEAF scripts.
Look [here](https://github.com/VEAF/VEAF-Mission-Creation-Tools/blob/76ca964c42366e62d597c6486da601b9fcb09eeb/src/scripts/veaf/veafAirWaves.lua#L1081C6-L1081C6) for example.
Ping me if you have questions.

**Comment by thomasbbrunner** [comment]
I see that you copy the tasks with `mist.getGroupRoute(groupName, 'task')`. Didn't know about this, thanks!

Did you ever notice drift in the position of the units using `mist.teleportToPoint` with the `clone` option?

**Comment by thomasbbrunner** [comment]
I'm keeping the issue open, as the drift in the position of bots when respawned using `mist.respawnGroup` is probably a bug.

**Comment by davidp57** [comment]
No, I didn’t.
But I never respawned 500 times either 😉

**Comment by mrSkortch** [comment]
If I had to guess that an error could compound over time because each time respawnGroup is called it uses the saved data for that group to be used as a template. Since it is an existing group some of that saved data might be updated on spawning of the group, which could change coordinates. I also haven't respawned anything 500 times. There have been compounding errors in the past, but they were occurring much sooner. 

Groups don't actually "teleport", its a new group using existing data it has access to. Unfortunately the exact tasks that are active for a given group cannot be queried. 

You should be able to use the optional value of `initTasks` and `offsetWP1` in teleportToPoint to get proper tasking behavior. For aircraft this is more important than for other AI types.  initTasks will keep the actual route tasking on the first waypoint regardless of where the group spawn. offsetWP1 will keep the rest of the route and tasks at any waypoint. 

When spawning a group it uses a vec2 and alt value instead of x, y, z (vec3). 
Random altitude occurs when the passed point is less than 10m AGL of the terrain. 


Personally if I was respawning a group like that I would use a more direct approach.
local gp = mist.getGroupTable("whatever")
mist.dynAdd(gp)

**Comment by thomasbbrunner** [comment]
Yes, we noticed that the error started earlier (maybe even from the first respawn) and compounds over time. It becomes very noticeable after hundreds of respawns though, as the airplane respawns in a completely different place. Interestingly enough, this only happens to bots and not to the player's airplane.

I'll use your suggested approach. Thanks for the many insights!

Feel free to close this issue, as this seems to be more of a problem with the underlying DCS API than with mist itself.
